In [ ]:
#Accuracy
#https://learn.galvanize.com/cohorts/182/units/2210/content_files/36410

	    y	           y_hat	                         acc
0	[0 1 0 0 0 1 0 0 0 1]	[0 0 0 0 1 0 1 1 1 0]	0.3
1	[1 0 1 1 1 1 1 1 1 1]	[0 0 1 1 1 0 1 0 0 0]	0.5
2	[0 0 1 1 1 1 1 0 1 1]	[0 1 0 1 0 1 1 0 0 0]	0.5
3	[0 0 0 0 0 1 1 0 1 1]	[1 1 0 1 0 1 1 1 0 1]	0.5
4	[0 1 0 1 0 0 1 0 1 1]	[1 1 1 1 1 1 1 1 1 0]	0.4
5	[0 1 1 1 1 1 1 1 1 0]	[1 0 1 1 0 1 0 1 1 0]	0.6
6	[1 0 1 0 0 1 1 0 1 1]	[1 0 0 0 0 0 0 0 0 0]	0.5
7	[1 0 1 1 1 0 0 0 0 1]	[0 0 0 0 0 1 0 1 0 1]	0.4
8	[0 0 1 1 1 0 1 0 0 1]	[1 0 0 1 1 1 0 0 0 0]	0.5
9	[0 0 1 0 0 0 1 0 0 1]	[0 0 0 0 0 1 1 1 0 0]	0.6


In [31]:
import numpy as np

M = 10
y_hat = np.random.randint(low=0, high=2, size=M)

y_hat


array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [32]:
y = np.random.randint(low=0, high=2, size=M)

y

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [33]:
def A(y_hat, y):
    return np.mean( y_hat == y )
    

In [34]:
error = np.mean( y_hat == y )

error

0.80000000000000004

In [8]:
# Edward's Learn asked us to define a function/method A as above.
#I tried doing it using scikit learn below.
#http://scikit-learn.org/stable/modules/model_evaluation.html
from sklearn.metrics import accuracy_score

accuracy_score(y, y_hat)

0.69999999999999996

In [ ]:
#Root Mean Square Error


In [35]:
import numpy as np

M = 10
y_hat = np.random.randn(M)

y_hat

array([-0.76673003,  0.55316061, -0.21775729, -1.20514002,  1.0809625 ,
        0.36604902,  0.1458618 ,  0.41585205, -1.51297796, -0.16605371])

In [36]:
y = np.random.randn(M)

y

array([ 0.48148267,  0.53439064,  0.07769914, -0.44280717, -0.05393061,
        0.01446144, -1.29913416,  0.65780214, -0.55645501,  0.24975993])

In [40]:
def R(y_hat, y):
    return np.sqrt(((y_hat - y) ** 2)).mean()
print (np.sqrt(((y_hat - y) ** 2)).mean())

0.687053527609


In [41]:
# https://stackoverflow.com/questions/17197492/root-mean-square-error-in-python
rms_val = R(np.array(y), np.array(y_hat))
print("rms error is: " + str(rms_val))

rms error is: 0.687053527609


In [42]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y, y_hat)

0.68728196447029555