In [ ]:
#Scalar Linear Regression

In [8]:
import numpy as np

w, b = np.random.randn(2)

w, b

(-1.6063763884104232, -0.41609235348769746)

In [9]:
x = np.random.randn()

x

-1.7316032574466578

In [14]:
def f(x, w, b):
    return ((x*w) + b)

In [16]:
print ((x*w) + b)

2.36551423337


In [ ]:
#Vectorized Linear Regression

In [6]:
import numpy as np

N = 2
w, b = np.random.randn(N), np.random.randn() # parameters


w


-0.15497811839187198

In [7]:
b

-0.15497811839187198

In [8]:
x = np.random.randn(N) # data point

def f(x, w, b):
    return x*w + b

In [11]:
x

array([ 0.68887277,  0.65408748])

In [10]:
print (x*w + b)

[-0.16871053 -0.80861986]


In [ ]:
# Multi class Logistic Regression

In [37]:
import numpy as np

N, C = 4, 2
W, b = np.random.randn(N, C), np.random.randn(C) # parameters


In [38]:
W, b

(array([[-0.01593394, -0.48604262],
        [-0.42882782,  1.26877487],
        [-0.87762829, -0.37744444],
        [-0.06101015, -1.04702314]]), array([-2.13556443, -0.64354574]))

In [39]:
x = np.random.randn(N) # data point

x

array([-0.10216049, -0.27254872,  1.34786774,  1.121304  ])

In [44]:
# https://www.codeproject.com/Articles/821347/MultiClass-Logistic-Classifier-in-Python
def f(x, w, b,):
    vec=np.dot(x,W.T);
    vec=np.add(vec,b);
    vec1=np.exp(vec);
    res=vec1.T/np.sum(vec1,axis=1);
    return res.T;
   


In [49]:
testa = np.array([[1 , 2], [3, 4]])

In [52]:
testa

array([[1, 2],
       [3, 4]])

In [53]:
testa+np.array([1,2])

array([[2, 4],
       [4, 6]])

In [45]:
f(x,w,b)

ValueError: shapes (4,) and (2,4) not aligned: 4 (dim 0) != 2 (dim 0)