In [ ]:
#Squared Loss



In [1]:
import numpy as np

M = 10
y_hat = np.random.randn(M)

y_hat

array([ 0.78698116, -0.45844389,  0.05869522,  2.03603757,  0.17834572,
       -0.1124619 ,  0.31261354,  0.35597135,  0.55557214,  0.04094916])

In [2]:
y = np.random.randn(M)

y

array([-0.78998989, -1.23763594, -0.35476719,  1.06263627, -0.61397898,
       -1.95398721, -0.2144136 , -0.71680905,  0.56283832,  0.095756  ])

In [4]:
#http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
from sklearn.metrics import mean_squared_error
def R(y_hat, y):
    return mean_squared_error(y, y_hat)
print  (mean_squared_error(y, y_hat) ) 

0.966310506506


In [ ]:
#Log Loss Function

In [36]:
import numpy as np
from sklearn.metrics import log_loss


p1 = np.random.uniform(0,1,10)

p1

array([ 0.72474969,  0.72242642,  0.45389613,  0.81713647,  0.04404475,
        0.48287528,  0.31864993,  0.54532994,  0.08948515,  0.62194987])

In [37]:
y1 = np.random.randint(low=0, high=2, size=10)

y1

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1])

In [40]:
def L(p, y):
    return (y+np.log(p)+(1-y)*np.log(1-p))


In [41]:
L(p1, y1)

array([ 0.67807106,  0.67486029, -1.39483298,  0.79805084, -2.12254901,
       -1.38746807, -0.14366219,  0.39363573, -2.5074277 ,  0.52510421])

In [ ]:
#Batch Log Loss
#https://learn.galvanize.com/cohorts/182/units/2210/content_files/36411

In [42]:
import numpy as np

M = 10
s = np.random.randn(M)

s


array([ 0.54293419, -1.48976052, -0.36407643,  0.52671811,  1.51170673,
       -1.96791463,  2.03957921, -0.43079148,  1.97544235,  0.28873656])

In [43]:
p = np.exp(s) / np.exp(s).sum()

p

array([ 0.06647337,  0.00870682,  0.02683725,  0.06540413,  0.17513796,
        0.00539759,  0.29691518,  0.02510522,  0.27846981,  0.05155266])

In [44]:
y = np.random.randint(low=0, high=2, size=M)

y

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0])

In [45]:
def L(p, y):
    return -1/len(y) * (np.sum(y*np.log(p)+(1-y)*np.log(1-p)))
 

In [46]:
print (-1/len(y) * (np.sum(y*np.log(p)+(1-y)*np.log(1-p))))


2.25378197311


In [ ]:
#Single Categorical Cross Entropy